kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-datadir
  labels:
    app: minecraft
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi