apiVersion: v1
kind: Service
metadata:
  name: minecraft-rcon
  labels:
    app: minecraft
spec:
  type: ClusterIP 
  ports:
  - name: rcon
    port: 28016
    targetPort: rcon
    protocol: TCP
  selector:
    app: minecraft